name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: Run Tests and Coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.11', '3.12']
        toxenv: [quality, docs, django42, django51]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r requirements/pip.txt

    - name: Install tox
      run: pip install tox

    - name: Run Tox
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.12' && matrix.toxenv == 'django42'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: true
