name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  python-tests:
    name: Run Python Tests and Coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12"]
        toxenv: [quality, docs, django42, django52]

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements/pip.txt tox

      - name: Run tests with Tox (${{ matrix.toxenv }})
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.12' && matrix.toxenv == 'django42'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
